name: proteinbert_gen
channels:
  - nvidia
  - pytorch
  - pyg
  - conda-forge
platforms:
  - osx-64
  - linux-64
dependencies:
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - lightning=2.2.0.post0
  - lightning-utilities=0.10.1
  - openssl=3.2.1
  - pyg=2.4.0
  - python=3.11.7
  - pytorch=2.1.2
  - pytorch-lightning=2.1.3
  - pytorch-cuda=12.1 # [linux64]
  - einops=0.8.0
  - pip
